class ExerciseModel {
  final String id;
  final String title;
  final String icon;
  final String duration;
  final String phase;
  final String description;
  final String science;
  final String detailedDuration;
  final List<String> preparationSteps;
  final List<ExerciseStep> exerciseSteps;
  final ExerciseTimerType timerType;

  ExerciseModel({
    required this.id,
    required this.title,
    required this.icon,
    required this.duration,
    required this.phase,
    required this.description,
    required this.science,
    required this.detailedDuration,
    required this.preparationSteps,
    required this.exerciseSteps,
    required this.timerType,
  });
}

class ExerciseStep {
  final String instruction;
  final int durationSeconds;
  final String? visualCue;

  ExerciseStep({
    required this.instruction,
    required this.durationSeconds,
    this.visualCue,
  });
}

enum ExerciseTimerType {
  cycle,
  countdown,
  selfPaced,
  segmented,
  twoPhase,
}

final List<ExerciseModel> allExercises = [
  ExerciseModel(
    id: '1',
    title: 'The 4-7-8 Technique',
    icon: '💨',
    duration: '2-3 min',
    phase: 'Phase 1',
    description: 'A powerful breathing technique that calms your nervous system by controlling your breath in a specific pattern.',
    science: 'Activates the parasympathetic nervous system, reducing stress hormones and promoting relaxation.',
    detailedDuration: '4-6 cycles (approximately 2-3 minutes)',
    preparationSteps: [
      'Find a comfortable seated position',
      'Place the tip of your tongue behind your upper front teeth',
      'Exhale completely through your mouth',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Breathe in through your nose', durationSeconds: 4),
      ExerciseStep(instruction: 'Hold your breath', durationSeconds: 7),
      ExerciseStep(instruction: 'Exhale through your mouth', durationSeconds: 8),
    ],
    timerType: ExerciseTimerType.cycle,
  ),
  ExerciseModel(
    id: '2',
    title: 'Cold Water Shock',
    icon: '🌊',
    duration: '60 sec',
    phase: 'Phase 1',
    description: 'Use cold water to trigger your vagus nerve and interrupt craving pathways instantly.',
    science: 'Triggers the vagus nerve response, interrupting the neural pathway of cravings and providing immediate relief.',
    detailedDuration: '60 seconds total',
    preparationSteps: [
      'Get a glass of ice-cold water ready',
      'Have a towel nearby if splashing face',
      'Take a moment to focus on the present',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Take a sip of ice-cold water and hold it in your mouth', durationSeconds: 10),
      ExerciseStep(instruction: 'Swallow slowly and feel the cold sensation', durationSeconds: 5),
      ExerciseStep(instruction: 'Splash cold water on your face or wrists', durationSeconds: 15),
      ExerciseStep(instruction: 'Take deep breaths and notice the refreshing feeling', durationSeconds: 30),
    ],
    timerType: ExerciseTimerType.countdown,
  ),
  ExerciseModel(
    id: '3',
    title: 'The 3-Minute Rule',
    icon: '⌛',
    duration: '3 min',
    phase: 'Phase 1',
    description: 'Wait out the craving peak with focused awareness. Most cravings naturally decrease after 3 minutes.',
    science: 'Cravings follow a predictable pattern, peaking and then naturally decreasing after the initial dopamine spike.',
    detailedDuration: '3 minutes countdown',
    preparationSteps: [
      'Acknowledge the craving without judgment',
      'Set your intention to wait it out',
      'Find something to focus on during the wait',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Notice and accept the craving', durationSeconds: 30),
      ExerciseStep(instruction: 'Focus on your breathing', durationSeconds: 60),
      ExerciseStep(instruction: 'Observe the craving intensity changing', durationSeconds: 60),
      ExerciseStep(instruction: 'Notice the craving weakening', durationSeconds: 30),
    ],
    timerType: ExerciseTimerType.countdown,
  ),
  ExerciseModel(
    id: '4',
    title: '5-4-3-2-1 Grounding',
    icon: '🔍',
    duration: '2-3 min',
    phase: 'Phase 1',
    description: 'Ground yourself in the present moment using all five senses to disrupt craving thoughts.',
    science: 'Engages the prefrontal cortex and disrupts the limbic system\'s craving response through sensory awareness.',
    detailedDuration: 'Self-paced (approximately 2-3 minutes)',
    preparationSteps: [
      'Look around your environment',
      'Take a comfortable position',
      'Prepare to engage all your senses',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Name 5 things you can see', durationSeconds: 30),
      ExerciseStep(instruction: 'Name 4 things you can touch', durationSeconds: 30),
      ExerciseStep(instruction: 'Name 3 things you can hear', durationSeconds: 30),
      ExerciseStep(instruction: 'Name 2 things you can smell', durationSeconds: 30),
      ExerciseStep(instruction: 'Name 1 thing you can taste', durationSeconds: 30),
    ],
    timerType: ExerciseTimerType.selfPaced,
  ),
  ExerciseModel(
    id: '5',
    title: 'Muscle Relaxation (PMR)',
    icon: '💆',
    duration: '8-10 min',
    phase: 'Phase 2',
    description: 'Systematically tense and release muscle groups from toes to face for deep relaxation.',
    science: 'Reduces cortisol levels and activates GABA neurotransmitters, promoting physical and mental relaxation.',
    detailedDuration: '8-10 minutes for full body scan',
    preparationSteps: [
      'Lie down or sit comfortably',
      'Close your eyes or soften your gaze',
      'Take three deep breaths to begin',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Tense your toes and feet', durationSeconds: 10),
      ExerciseStep(instruction: 'Release and relax your feet', durationSeconds: 10),
      ExerciseStep(instruction: 'Tense your calves', durationSeconds: 10),
      ExerciseStep(instruction: 'Release and relax your calves', durationSeconds: 10),
      ExerciseStep(instruction: 'Tense your thighs', durationSeconds: 10),
      ExerciseStep(instruction: 'Release and relax your thighs', durationSeconds: 10),
      ExerciseStep(instruction: 'Tense your abdomen', durationSeconds: 10),
      ExerciseStep(instruction: 'Release and relax your abdomen', durationSeconds: 10),
      ExerciseStep(instruction: 'Tense your arms', durationSeconds: 10),
      ExerciseStep(instruction: 'Release and relax your arms', durationSeconds: 10),
      ExerciseStep(instruction: 'Tense your shoulders', durationSeconds: 10),
      ExerciseStep(instruction: 'Release and relax your shoulders', durationSeconds: 10),
      ExerciseStep(instruction: 'Tense your face', durationSeconds: 10),
      ExerciseStep(instruction: 'Release and relax completely', durationSeconds: 30),
    ],
    timerType: ExerciseTimerType.segmented,
  ),
  ExerciseModel(
    id: '6',
    title: 'Bilateral Stimulation',
    icon: '🔍',
    duration: '2-3 min',
    phase: 'Phase 2',
    description: 'Cross your arms and tap alternating shoulders, or march in place to activate both brain hemispheres.',
    science: 'Activates both brain hemispheres simultaneously, similar to EMDR therapy effects, reducing emotional intensity.',
    detailedDuration: '2-3 minutes of alternating movement',
    preparationSteps: [
      'Stand or sit comfortably',
      'Cross your arms over your chest',
      'Prepare for rhythmic movement',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Tap your right shoulder with left hand', durationSeconds: 2),
      ExerciseStep(instruction: 'Tap your left shoulder with right hand', durationSeconds: 2),
      ExerciseStep(instruction: 'Continue alternating taps rhythmically', durationSeconds: 120),
    ],
    timerType: ExerciseTimerType.countdown,
  ),
  ExerciseModel(
    id: '7',
    title: 'Finger Pressure Points',
    icon: '👈',
    duration: '60 sec',
    phase: 'Phase 2',
    description: 'Apply firm pressure between your thumb and index finger to stimulate acupressure points.',
    science: 'Stimulates the LI4 acupoint, releasing endorphins and reducing stress-related cravings.',
    detailedDuration: '60 seconds of sustained pressure',
    preparationSteps: [
      'Locate the webbing between thumb and index finger',
      'Prepare to apply firm but comfortable pressure',
      'Breathe normally throughout',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Apply firm pressure to the point', durationSeconds: 20),
      ExerciseStep(instruction: 'Maintain steady pressure', durationSeconds: 20),
      ExerciseStep(instruction: 'Gently massage in circles', durationSeconds: 20),
    ],
    timerType: ExerciseTimerType.countdown,
  ),
  ExerciseModel(
    id: '8',
    title: 'Rapid distraction',
    icon: '⚡',
    duration: '60 sec',
    phase: 'Phase 2',
    description: 'A quick physical reset: STOP what you\'re doing, DROP your shoulders, and ROLL them back.',
    science: 'Physical movement interrupts automatic behavior circuits and releases tension instantly.',
    detailedDuration: '30 seconds quick routine',
    preparationSteps: [
      'Stand or sit up straight',
      'Notice any tension in your shoulders',
      'Prepare for quick movements',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'STOP - Freeze your current position', durationSeconds: 5),
      ExerciseStep(instruction: 'DROP - Let your shoulders fall', durationSeconds: 5),
      ExerciseStep(instruction: 'ROLL - Roll shoulders backward 3 times', durationSeconds: 10),
      ExerciseStep(instruction: 'Take a deep breath and reset', durationSeconds: 10),
    ],
    timerType: ExerciseTimerType.countdown,
  ),
  ExerciseModel(
    id: '9',
    title: 'Stop-Drop-Roll',
    icon: '🔄',
    duration: '30 sec',
    phase: 'Phase 2',
    description: 'A quick physical reset: STOP what you\'re doing, DROP your shoulders, and ROLL them back.',
    science: 'Physical movement interrupts automatic behavior circuits and releases tension instantly.',
    detailedDuration: '30 seconds quick routine',
    preparationSteps: [
      'Stand or sit up straight',
      'Notice any tension in your shoulders',
      'Prepare for quick movements',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'STOP - Freeze your current position', durationSeconds: 5),
      ExerciseStep(instruction: 'DROP - Let your shoulders fall', durationSeconds: 5),
      ExerciseStep(instruction: 'ROLL - Roll shoulders backward 3 times', durationSeconds: 10),
      ExerciseStep(instruction: 'Take a deep breath and reset', durationSeconds: 10),
    ],
    timerType: ExerciseTimerType.countdown,
  ),
  ExerciseModel(
    id: '10',
    title: 'Rapid Eye Movement',
    icon: '👀',
    duration: '1-2 min',
    phase: 'Phase 3',
    description: 'Move your eyes rapidly in different directions to disrupt focused craving thoughts.',
    science: 'Disrupts focused craving thoughts and reduces intrusive thinking through eye movement desensitization.',
    detailedDuration: '40 movements total (10 in each direction)',
    preparationSteps: [
      'Sit comfortably with head still',
      'Keep your head facing forward',
      'Move only your eyes',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Look far left 10 times', durationSeconds: 20),
      ExerciseStep(instruction: 'Look far right 10 times', durationSeconds: 20),
      ExerciseStep(instruction: 'Look up 10 times', durationSeconds: 20),
      ExerciseStep(instruction: 'Look down 10 times', durationSeconds: 20),
    ],
    timerType: ExerciseTimerType.segmented,
  ),
  ExerciseModel(
    id: '11',
    title: 'Lemon Visualization',
    icon: '🍋',
    duration: '2-3 min',
    phase: 'Phase 3',
    description: 'Vividly imagine biting into a sour lemon to activate taste centers and override cravings.',
    science: 'Activates taste centers in the brain, crowding out nicotine craving signals through sensory imagination.',
    detailedDuration: '2-3 minutes guided visualization',
    preparationSteps: [
      'Close your eyes or soften your gaze',
      'Take a comfortable seated position',
      'Prepare to engage your imagination',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Imagine holding a bright yellow lemon', durationSeconds: 30),
      ExerciseStep(instruction: 'Picture cutting it in half', durationSeconds: 20),
      ExerciseStep(instruction: 'Imagine bringing it to your mouth', durationSeconds: 20),
      ExerciseStep(instruction: 'Feel the sour juice on your tongue', durationSeconds: 30),
      ExerciseStep(instruction: 'Notice your mouth watering', durationSeconds: 20),
      ExerciseStep(instruction: 'Let the sensation fade gradually', durationSeconds: 30),
    ],
    timerType: ExerciseTimerType.countdown,
  ),
  ExerciseModel(
    id: '12',
    title: 'Hand Warming',
    icon: '🤲',
    duration: '1 min',
    phase: 'Phase 3',
    description: 'Rub your hands together vigorously, then place them on your cheeks for warmth and comfort.',
    science: 'Increases blood flow and reduces stress-induced vasoconstriction, promoting relaxation.',
    detailedDuration: '1 minute (30 seconds each phase)',
    preparationSteps: [
      'Sit or stand comfortably',
      'Remove any rings if wearing',
      'Prepare for vigorous movement',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Rub hands together vigorously', durationSeconds: 30),
      ExerciseStep(instruction: 'Place warm hands on your cheeks', durationSeconds: 30),
    ],
    timerType: ExerciseTimerType.twoPhase,
  ),
  // NEW EXERCISES - Phase 1 additions (3)
  ExerciseModel(
    id: '13',
    title: 'Box Breathing Technique',
    icon: '⬜',
    duration: '4 min',
    phase: 'Phase 1',
    description: 'Military-grade breathing technique using equal counts for inhale, hold, exhale, and hold to reset your nervous system.',
    science: 'Activates the parasympathetic nervous system and increases vagal tone, reducing stress hormones by up to 50% within minutes.',
    detailedDuration: '16 cycles (4 minutes total)',
    preparationSteps: [
      'Sit upright with feet flat on floor',
      'Rest hands comfortably on your lap',
      'Visualize drawing a square as you breathe',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Inhale through nose', durationSeconds: 4),
      ExerciseStep(instruction: 'Hold breath', durationSeconds: 4),
      ExerciseStep(instruction: 'Exhale through mouth', durationSeconds: 4),
      ExerciseStep(instruction: 'Hold empty', durationSeconds: 4),
    ],
    timerType: ExerciseTimerType.cycle,
  ),
  ExerciseModel(
    id: '14',
    title: 'Urge Surfing',
    icon: '🏄',
    duration: '3-5 min',
    phase: 'Phase 1',
    description: 'Ride out the craving wave by observing it rise, peak, and fall without acting on it.',
    science: 'Based on mindfulness research showing cravings naturally subside after 3-5 minutes when observed without judgment.',
    detailedDuration: '3-5 minutes of mindful observation',
    preparationSteps: [
      'Acknowledge the craving without resistance',
      'Imagine the craving as an ocean wave',
      'Commit to "surfing" rather than fighting',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Notice where you feel the craving in your body', durationSeconds: 60),
      ExerciseStep(instruction: 'Observe the craving intensity rising', durationSeconds: 60),
      ExerciseStep(instruction: 'Stay with the peak sensation', durationSeconds: 60),
      ExerciseStep(instruction: 'Notice the craving beginning to fall', durationSeconds: 60),
      ExerciseStep(instruction: 'Feel the wave passing', durationSeconds: 60),
    ],
    timerType: ExerciseTimerType.selfPaced,
  ),
  ExerciseModel(
    id: '15',
    title: 'Quick Body Scan',
    icon: '🎯',
    duration: '2 min',
    phase: 'Phase 1',
    description: 'Rapidly scan your body from head to toe, releasing tension and redirecting focus from cravings.',
    science: 'MBSR studies show body scanning reduces cortisol and increases body awareness, disrupting automatic craving responses.',
    detailedDuration: '2 minutes systematic scan',
    preparationSteps: [
      'Stand or sit comfortably',
      'Close your eyes or soften your gaze',
      'Take one deep breath to begin',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Focus on your head and face', durationSeconds: 20),
      ExerciseStep(instruction: 'Notice your neck and shoulders', durationSeconds: 20),
      ExerciseStep(instruction: 'Scan your chest and arms', durationSeconds: 20),
      ExerciseStep(instruction: 'Feel your abdomen and back', durationSeconds: 20),
      ExerciseStep(instruction: 'Notice your hips and legs', durationSeconds: 20),
      ExerciseStep(instruction: 'Feel your feet grounded', durationSeconds: 20),
    ],
    timerType: ExerciseTimerType.segmented,
  ),
  // NEW EXERCISES - Phase 2 additions (3)
  ExerciseModel(
    id: '16',
    title: 'Counting Backwards',
    icon: '🔢',
    duration: '2 min',
    phase: 'Phase 2',
    description: 'Count backwards from 100 by 7s to engage your cognitive brain and override craving impulses.',
    science: 'Engages the prefrontal cortex in mathematical processing, reducing activity in the addiction-related reward centers.',
    detailedDuration: '2 minutes of mental math',
    preparationSteps: [
      'Find a quiet spot to focus',
      'Start with the number 100',
      'Prepare to subtract 7 each time',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Start counting: 100, 93, 86...', durationSeconds: 30),
      ExerciseStep(instruction: 'Continue: 79, 72, 65...', durationSeconds: 30),
      ExerciseStep(instruction: 'Keep going: 58, 51, 44...', durationSeconds: 30),
      ExerciseStep(instruction: 'Finish strong: 37, 30, 23...', durationSeconds: 30),
    ],
    timerType: ExerciseTimerType.countdown,
  ),
  ExerciseModel(
    id: '17',
    title: 'Heart Coherence',
    icon: '❤️',
    duration: '3 min',
    phase: 'Phase 2',
    description: 'Synchronize your breathing with your heartbeat using the 5-5 rhythm for emotional balance.',
    science: 'Heart rate variability training improves vagal tone and reduces stress hormones, proven effective in addiction recovery.',
    detailedDuration: '3 minutes of coherent breathing',
    preparationSteps: [
      'Place hand over your heart',
      'Focus on your heartbeat',
      'Begin steady breathing',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Breathe in for 5 counts', durationSeconds: 5),
      ExerciseStep(instruction: 'Breathe out for 5 counts', durationSeconds: 5),
    ],
    timerType: ExerciseTimerType.cycle,
  ),
  ExerciseModel(
    id: '18',
    title: 'Jaw Release Technique',
    icon: '😮',
    duration: '90 sec',
    phase: 'Phase 2',
    description: 'Release tension in your jaw and facial muscles where stress from cravings often accumulates.',
    science: 'The jaw holds significant tension during nicotine withdrawal. Releasing it activates the parasympathetic response.',
    detailedDuration: '90 seconds of targeted release',
    preparationSteps: [
      'Notice any jaw tension',
      'Sit or stand comfortably',
      'Prepare to open mouth wide',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Open mouth wide and yawn', durationSeconds: 10),
      ExerciseStep(instruction: 'Move jaw side to side gently', durationSeconds: 20),
      ExerciseStep(instruction: 'Massage jaw muscles with fingers', durationSeconds: 30),
      ExerciseStep(instruction: 'Let jaw hang loose and relaxed', durationSeconds: 30),
    ],
    timerType: ExerciseTimerType.countdown,
  ),
  // NEW EXERCISES - Phase 3 additions (2)
  ExerciseModel(
    id: '19',
    title: 'Vocal Toning',
    icon: '🎵',
    duration: '2 min',
    phase: 'Phase 3',
    description: 'Use humming and vocal vibrations to stimulate the vagus nerve and calm your system.',
    science: 'Vocal vibrations directly stimulate the vagus nerve through the larynx, increasing parasympathetic activity by 30%.',
    detailedDuration: '2 minutes of vocal exercises',
    preparationSteps: [
      'Sit upright with relaxed shoulders',
      'Take a deep breath',
      'Prepare to make humming sounds',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Hum deeply with lips closed', durationSeconds: 30),
      ExerciseStep(instruction: 'Try different pitches', durationSeconds: 30),
      ExerciseStep(instruction: 'Chant "Om" slowly', durationSeconds: 30),
      ExerciseStep(instruction: 'Return to gentle humming', durationSeconds: 30),
    ],
    timerType: ExerciseTimerType.segmented,
  ),
  ExerciseModel(
    id: '20',
    title: 'Temperature Reset',
    icon: '🌡️',
    duration: '90 sec',
    phase: 'Phase 3',
    description: 'Alternate between holding ice and warm objects to reset your sensory system and distract from cravings.',
    science: 'Temperature contrast therapy triggers thermoreceptors, overriding craving signals through sensory gating.',
    detailedDuration: '90 seconds of temperature alternation',
    preparationSteps: [
      'Get ice cubes and warm water',
      'Have a towel ready',
      'Prepare both hands',
    ],
    exerciseSteps: [
      ExerciseStep(instruction: 'Hold ice cube in right hand', durationSeconds: 20),
      ExerciseStep(instruction: 'Switch ice to left hand', durationSeconds: 20),
      ExerciseStep(instruction: 'Dip hands in warm water', durationSeconds: 20),
      ExerciseStep(instruction: 'Hold ice in both hands', durationSeconds: 15),
      ExerciseStep(instruction: 'Warm hands by rubbing together', durationSeconds: 15),
    ],
    timerType: ExerciseTimerType.countdown,
  ),
];